// this file contains the constant metadata strings
// constant metadata for SLQGetTypeInfo
const char type_info_query_meta[] = 
            "{\"signature\":{\
              \"name\":[\"TYPE_NAME\",\
                        \"DATA_TYPE\",\
                        \"COLUMN_SIZE\",\
                        \"LITERAL_PREFIX\",\
                        \"LITERAL_SUFFIX\",\
                        \"CREATE_PARAMS\",\
                        \"NULLABLE\",\
                        \"CASE_SENSITIVE\",\
                        \"SEARCHABLE\",\
                        \"UNSIGNED_ATTRIBUTE\",\
                        \"FIXED_PREC_SCALE\",\
                        \"AUTO_UNIQUE_VALUE\",\
                        \"LOCAL_TYPE_NAME\",\
                        \"MINIMUM_SCALE\",\
                        \"MAXIMUM_SCALE\",\
                        \"SQL_DATA_TYPE\",\
                        \"SQL_DATETIME_SUB\",\
                        \"NUM_PREC_RADIX\",\
                        \"INTERVAL_PRECISION\"\
                        ]\
              ,\"type\":[\"string?\",\
                        \"int16?\",\
                        \"int32?\",\
                        \"string?\",\
                        \"string?\",\
                        \"string?\",\
                        \"int16?\",\
                        \"int16?\",\
                        \"int16?\",\
                        \"int16?\",\
                        \"int16?\",\
                        \"int16?\",\
                        \"string?\",\
                        \"int16?\",\
                        \"int16?\",\
                        \"int16?\",\
                        \"int16?\",\
                        \"int32?\",\
                        \"int16?\"\
                        ]}}";